House Price Prediction - With Multiple Features (area, bedrooms, age)

At the very 1st, we have to analyze the datasets.
If there are any missing values, we first have to tackle this thing.
Look for the linear relationship between the variable and target feature. Analyse the data to know the insights.

Since our target variable(price) is dependent on 3 variables that are age,bedrooms and age, so our linear equation of multivariables will be:

price = theta1 * area + theta2 * bedrooms + theta3 * age + b

Topics:
1. Data Preprocessing: Handling NA Values
2. Linear Regression using Multiple Variables

01 - Data Preprocessing

In [2]:
# importing the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
# loading the data
df = pd.read_csv("mldata2.csv")
df

   area  bedrooms  age   price
0  2000       2.0   15  600000
1  2400       3.0   20  615000
2  2600       NaN   23  665000
3  3000       2.0   35  650000
4  3400       4.0    3  810000

To handle the missing values, I will take the median. It depends on the column whether to take the median or mean to fill the missing values.

First, the distribution of that column should be checked using "df['column_name'].hist()". If the distribution is skewed, its always a good idea to use median as this is robust to outliers. Whereas for symmetric distribution, mean is also ok.

Also, Check the %age of missing values:
If very few missing (<5%); median/mean is fine.
If many missing; consider more advanced methods

In [8]:
# df.bedrooms.median()
#Since our data has no decimal values, so to have simple zero decimal value median, we will use floor function.
import math
median_value = math.floor(df.bedrooms.median())
median_value

2

In [9]:
#Now, fill the missing values of the bedroom column with median_value
df.bedrooms.fillna(median_value)

0    2.0
1    3.0
2    2.0
3    2.0
4    4.0
Name: bedrooms, dtype: float64

In [11]:
#Now to assign this back to original dataframe, we do this.
df.bedrooms = df.bedrooms.fillna(median_value)
df

   area  bedrooms  age   price
0  2000       2.0   15  600000
1  2400       3.0   20  615000
2  2600       2.0   23  665000
3  3000       2.0   35  650000
4  3400       4.0    3  810000

So, till now, our Data Preprocessing step is Over.

02 - Linear Regression using Multi-Variable

In [12]:
# training the model
reg = linear_model.LinearRegression() #created an object for the model
reg.fit(df[['area', 'bedrooms', 'age']],df.price) #remember X_train is always 2D here

LinearRegression()

In [27]:
# predicting the price of the house based on the 3 variables
reg.predict([[2500,3,10]]) #area=2500, bedrooms= 3, age=10
# also remember the argument to predict function is always given as 2D array.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([674850.])

In [28]:
#always a good idea to know the coefficients and intercept to cross check
reg.coef_

array([   144.92857143, -27517.34693878,  -4776.53061224])

In [29]:
reg.intercept_

np.float64(442845.9183673457)

In [30]:
#crosschecking
#putting into price = theta1*area + theta2*bedrooms + theta3*age
(2500*144.92857143) + (3*-27517.34693878) + (10*(-4776.53061224)) + (442845.9183673457)

674850.0000036057

Analysis:

Notice that, with a house of area=2500, bedrooms= 3,and age=10. The price is higher than what we trained to the model in row 2 as area = 2600, bedrooms = 2, and age = 23; although the area of that row 2 is more. This is because, the age of predicted model is just 10 which is way less than the age of the house sample given in training with age = 20. Therefore, our model has correctly learnt the relation, did the right trade-off, and given the right price value to the house with the age = 10.

**Exercise**

In [53]:
#loading the data
df2 = pd.read_csv("hiring.csv")
df2

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

Since our data contains missing values, our first step should be Data Preprocessing.

01 - Data Preprocessing:

Notice here that the experience column is a word column although its literal meaning is a number. So, it would be best idea to convert words to number using "word2number" library. For the missing values in the experience column, we will assume 0 experience.

To handle missing values in test_score column, we will take the median

In [33]:
!pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=6808f0b0cde33c8e92742e9f24f1ad41660c40d517f36475aecf9efb25d2358c
  Stored in directory: /root/.cache/pip/wheels/5b/79/fb/d25928e599c7e11fe4e00d32048cd74933f34a74c633d2aea6
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [54]:
from word2number import w2n

#First, filling the experience column with string value 'zero'
df2['experience'] = df2['experience'].fillna('zero')
df2['experience']

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [55]:
#now converting all the string words to numbers
df2['experience'] = df2['experience'].apply(lambda x: w2n.word_to_num(x))
df2['experience']

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [61]:
# now converting filling the missing values of "test_score(out of 10)" column using median
medvalue = df2['test_score(out of 10)'].median()
medvalue

8.0

In [64]:
df2['test_score(out of 10)'] = df2['test_score(out of 10)'].fillna(medvalue)
df2

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

Till here, Data Preprocessing is done.

02 - Linear Regression using Multi Variables

In [66]:
# training the model
reg2 = linear_model.LinearRegression()
reg2.fit(df2[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df2[['salary($)']])

LinearRegression()

In [69]:
# predicting the salary with experience = 12, test_score = 10, interview_score = 10
reg2.predict([[12,10,10]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[92002.18340611]])

---------The End-----------